### PR TITLE
Fix: missing icons in 05 completion

### PR DESCRIPTION
**Pull request by vimnux**
Hereby a fix for the missing icons in cmd.lua 
(nerdfonts got an update and the recommended font is no longer available)

Haven't seen any issue #'s or PR #'s with it.

Thank you very much for this course !

### CODE REVIEW

**Comment by gnmearacaun** [comment]
These were meant for the completion branch if I'm not mistaken... also the `keyword` icon is broken for me. You can pick something else on the nerdfonts cheatsheet if you want

**Comment by vimnux** [comment]
Since I'm following the Youtube course, this is only for the 05-ompletion branch.

Replaced the missing keyword icon and updated the my05-completion branch. 

No idea why so many conflicting files ... here is the diff:


diff --git a/lua/user/cmp.lua b/lua/user/cmp.lua
index ae7df16..e877b16 100644
--- a/lua/user/cmp.lua
+++ b/lua/user/cmp.lua
@@ -15,33 +15,33 @@ local check_backspace = function()
   return col == 0 or vim.fn.getline("."):sub(col, col):match "%s"
 end
 
---   פּ ﯟ   some other good icons
+--   פּ ﯟ   some other good icons
 local kind_icons = {
-  Text = "",
+  Text = "󰊄",
   Method = "m",
-  Function = "",
+  Function = "󰊕",
   Constructor = "",
   Field = "",
-  Variable = "",
+  Variable = "󰫧",
   Class = "",
   Interface = "",
   Module = "",
   Property = "",
   Unit = "",
-  Value = "",
+  Value = "",
   Enum = "",
-  Keyword = "",
+  Keyword = "󰌆",
   Snippet = "",
-  Color = "",
-  File = "",
+  Color = "",
+  File = "",
   Reference = "",
-  Folder = "",
+  Folder = "",
   EnumMember = "",
-  Constant = "",
+  Constant = "",
   Struct = "",
   Event = "",
-  Operator = "",
-  TypeParameter = "",
+  Operator = "",
+  TypeParameter = "󰉺",
 }
 -- find more here: https://www.nerdfonts.com/cheat-sheet

**Comment by gnmearacaun** [comment]
It's because the pull request is against `master`

**Comment by vimnux** [comment]
The Class icon didn't look to good in my browser so I replaced that one in my latest push to the my05-completion branch.

**Comment by gnmearacaun** [comment]
I like your variable icon, it's better than what we use in `master`

Okay, but you still need to make the request against the completion branch, not `master`

**Comment by vimnux** [comment]
Thank you ! 

Made the new pull request: PR #310

**Pull request closed without merging**
