### PR TITLE
Address deprecation warnings

### LINKED ISSUE #294: sumneko_lua is deprecated, use lua_ls instead. See :h deprecated
Hello, i follow the fantastic NeoVim from Scratch Tutorial. I am a beginner in terms of NeoVim. 
From branch 06 there is the error message  "sumneko_lua is deprecated, use lua_ls instead."

I research a bit and found out, that this problem is due to renaming of the plugin. 
Will this be fixed in the repo, or will there be a guide, how to fix this? 

Thanks a lot
Michel

### PR DESCRIPTION
**Pull request by trekie86**
This change addresses deprecation warnings and updates cmp_nvim_lsp per https://github.com/hrsh7th/cmp-nvim-lsp/issues/38. Additional migration from sumneko_lua to lua_ls and the corresponding settings file.

fixes #294

### CODE REVIEW

**Comment by trekie86** [comment]
Addresses https://github.com/LunarVim/Neovim-from-scratch/issues/294

**Review by gnmearacaun — CHANGES_REQUESTED** [review]
Hi, thanks very much for fixing the error. ~~Could you fix the indent please.~~ nvm, your indent is fine, tabs are used on subsequent lines causing them to be expanded into multiple spaces on Github.

**Comment by trekie86** [comment]
Great thanks. I thought the spacing was accurate but I'll double check my nvim config to ensure it's replacing tabs with spaces to keep things consistent.

**Comment by trekie86** [comment]
This should be able to resolve #294 unless we should go through to address each impacted branch as well.

**Comment by gnmearacaun** [comment]
> Great thanks. I thought the spacing was accurate but I'll double check my nvim config to ensure it's replacing tabs with spaces to keep things consistent.

For sure, it's configured in options to expand tabs to (2) spaces. Github has a default set to 8 spaces, which is why it appears janky. The repo uses spaces (vs tabs) by default. The default can be changed in the Github user `Settings > Appearance` to change the default to two spaces, if desired. A few of the files are using tabs due to various authors including parts copied from other repos. There's a handy command `:retab` to replace tabs with spaces in a file. That's something we ought to do (including your fix above) in `master` in the fullness of time.

**Comment by gnmearacaun** [comment]
> This should be able to resolve #294 unless we should go through to address each impacted branch as well.

Thanks, I've closed #294 now.

There are other problems with all of the later branches. Stuff that has been fixed already in `master` but just needs to be applied to those branches.

**Pull request merged**
