### PR TITLE
[FIX] Tree-sitter ensure_installed error message

### PR DESCRIPTION
**Pull request by rohanghige**

### CODE REVIEW

**Comment by rohanghige** [comment]
Fixing the nvim startup screen error

**Review by gnmearacaun — COMMENTED** [review]
since `maintained` isn't supported you could change the comment to
```
-- A list of parser names, or "all"
```

**Comment by rohanghige** [comment]
@gnmearacaun Rectified the comment as well and few others as well.

**Review by gnmearacaun — COMMENTED** [review]
https://github.com/LunarVim/Neovim-from-scratch/pull/152/commits/219abb0e6866a6f33f5332cc00ff22bcef1a9a63 was not merged and is still giving errors for stock users of the config. @rohanghige ~can you reopen the pull request?~ This is covered in open PR #131

**Pull request merged**
