### PR TITLE
cmp.lua fix for Neovim 0.7

### PR DESCRIPTION
**Pull request by sottoms**
Reference: https://www.reddit.com/r/neovim/comments/u5onwt/how_so_i_resolve_the_documentation_is_deprecated/i537wiu/?utm_source=share&utm_medium=web2x&context=3

### CODE REVIEW

**Comment by aflyingpumpkin** [comment]
#117 #115 #112

This also contains way more than just fixing `cmp.lua`

**Comment by gnmearacaun** [comment]
Agreed, it will be simpler to merge if you just work on one issue at a time.

**Review by gnmearacaun — CHANGES_REQUESTED** [review]
some of these commits are fixed in #146 and #162. To be tidy, perhaps close this PR @sottoms ? You could create a new feature branch off of current master branch for your latex contribution tyvm

**Comment by sottoms** [comment]
Closing pull request per comments.

**Pull request closed without merging**
