### PR TITLE
update toggleterm with python3

### PR DESCRIPTION
**Pull request by fdelacruz**

### CODE REVIEW

**Comment by dvchoudh** [comment]
This change can be an issue for Windows users, since typing `python3` on Windows would re-direct to the Microsoft Store to download Python from there (which you shouldn't do). Just typing `python` on Mac/Linux should suffice.

**Comment by fdelacruz** [comment]
I see what you are saying, but `python` on a mac defaults to the system original binary, which as of this writing is Python 2.7.16. Everybody updates it to Python 3 which AFAIK goes by `python3`.

**Comment by dvchoudh** [comment]
Can you implement a system dependent function then? That should work out.

**Comment by laloch** [comment]
> This change can be an issue for Windows users, since typing `python3` on Windows would re-direct to the Microsoft Store to download Python from there (which you shouldn't do). Just typing `python` on Mac/Linux should suffice.

Not only for Windows users. Users of sane Linux distributions don't have `python3` either.

**Pull request closed without merging**
